import CartPage from "@/components/order/cart";
import ColiesTable from "@/components/order/tracking";
import Pagination from "@/components/products/options/pagination";
import { ClientOrders } from "@/lib/endpoint/order";
import { Metadata } from "next";
import { notFound } from "next/navigation";

export const metadata: Metadata = {
    title: "Tracking",
    description: "Generated by create next app",
};

type props = {
    searchParams: Promise<{ page?: string, num?: string }>;
}


export default async function Cart({ searchParams }: props) {

    const { page, num } = await searchParams;
    const pageNumber = page ?? "1";
    const trackingNum = num ?? "0";

    const clientOrders = await ClientOrders({ num: trackingNum, page: pageNumber })

    if (!clientOrders) notFound()

    const { result, totalAct, count } = clientOrders

    return (
        <div>
            <ColiesTable colis={result} totalColis={count} />;
            <Pagination pages={totalAct} currentPage={Number(pageNumber)} params={`&num=${trackingNum}`} />
        </div>
    )
}