import SingleProduct from '@/components/products/single-product'
import { SingleProducts } from '@/lib/endpoint/product';
import { Metadata } from 'next';
import { notFound } from 'next/navigation';
import React from 'react'

type Params = {
    params: Promise<{ product: string }>
}

export const metadata: Metadata = {
    title: "Product",
    description: "Generated by create next app",
};

export default async function SinglePage({ params }: Params) {

    const { product } = await params;

    const single = await SingleProducts(product)

    if (!single) notFound()

    return (
        <div>
            <SingleProduct product={single} />
        </div>
    )
}
