import NeonSign from "@/components/personalizer/text_neo";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Personalizer",
    description: "Generated by create next app",
};


export default function Home() {
    return <NeonSign />;
}