import CartPage from "@/components/order/cart";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Cart",
    description: "Generated by create next app",
};


export default function Cart() {
    return <CartPage />;
}