import Pagination from '@/components/products/options/pagination';
import Products from '@/components/products/products';
import { AllProducts } from '@/lib/endpoint/product';
import { Metadata } from 'next';
import { notFound } from 'next/navigation';
import React from 'react'

export const metadata: Metadata = {
  title: "Products",
  description: "Generated by create next app",
};

type props = {
  searchParams: Promise<{ page?: string, search?: string, category?: string }>;
}


export default async function ProductPage({ searchParams }: props) {

  const { page, search, category } = await searchParams;
  const pageNumber = page ?? "1";
  const search_num = search ?? "";
  const searchCategory = category ?? "";

  const product = await AllProducts({ page: pageNumber, title: search_num, category: searchCategory })

  if (!product) notFound()

  const { result, totalAct } = product

  return (
    <div>
      <Products products={result} />
      <Pagination pages={totalAct} currentPage={Number(pageNumber)} params={`&search=${search_num}&category=${searchCategory}`} />
    </div>
  )
}
