import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
  title: "Products",
  description: "Generated by create next app",
};


export default function ProductPage() {
  return (
    <div>

    </div>
  )
}
