import Products from '@/components/products/products';
import { AllProducts } from '@/lib/endpoint/product';
import { Metadata } from 'next';
import { notFound } from 'next/navigation';
import React from 'react'

export const metadata: Metadata = {
  title: "Products",
  description: "Generated by create next app",
};


export default async function ProductPage() {

  const product = await AllProducts()

  if (!product) notFound()

  const { result } = product

  return (
    <div>
      <Products products={result} />
    </div>
  )
}
