name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.17.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env:
      SERVER_DOMAIN: ${{ secrets.SERVER_DOMAIN }}
      IMGS_DOMAIN: ${{ secrets.IMGS_DOMAIN }}

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm dedupe
    - run: npm run build --if-present

    - name: Change Directory
      run: cd /home/perfect/perfect-runner/_work/perfect-room/perfect-room
    - run: pm2 reload 1
